Repository spatialos/gdk-for-unity-blank-project, pull requests merged in 2020-06, with the labels that each got.

#103 Enable Accelerator
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/shared-ci.pinned
Labels: jira/no-ticket, size/S

#104 Update pin
  ci/shared-ci.pinned
Labels: jira/no-ticket, size/XS

#105 New Buildkite instrumentation format
  ci/bootstrap.sh
  ci/get-shared-ci.sh
  ci/launch.sh
  ci/lint.sh
  ci/shared-ci.pinned
Labels: jira/no-ticket, size/M

#106 Disable MacOS Agents temporarily due to broken agents
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/M

#107 Remove xr legacyinputhelpers package from manifest
  CHANGELOG.md
  workers/unity/Packages/manifest.json
Labels: jira/no-ticket, size/XS
