Repository spatialos/gdk-for-unity-blank-project, pull requests merged in 2020-02, with the labels that each got.

#85 Remove packer config
  packer.config.json
Labels: jira/no-ticket, size/S

#86 Move iOS ci to MacOS
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/premerge.steps.yaml
  ci/bootstrap.sh
  ci/shared-ci.pinned
Labels: jira/no-ticket, size/M

#87 Update release QA script
  ci/launch.sh
  gdk.pinned
Labels: jira/no-ticket, size/XS

#88 Feature/linting
  .buildkite/premerge.steps.yaml
  .editorconfig
  ci/bootstrap.sh
  ci/get-shared-ci.sh
  ci/lint.sh
  ci/shared-ci.pinned
  workers/unity/Assets/BlankProject/Scripts/Workers/UnityClientConnector.cs
  workers/unity/Assets/BlankProject/Scripts/Workers/UnityGameLogicConnector.cs
Labels: jira/no-ticket, size/M
