Repository spatialos/gdk-for-unity-blank-project, pull requests merged in 2020-08, with the labels that each got.

#117 UTY-2646: new dotnet version
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/shared-ci.pinned
  gdk.pinned
Labels: jira/UTY, size/XS

#122 Unity 2020.1 Upgrade
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  gdk.pinned
  workers/unity/.gitignore
  workers/unity/Packages/manifest.json
  workers/unity/ProjectSettings/ProjectVersion.txt
  workers/unity/ProjectSettings/VersionControlSettings.asset
Labels: jira/no-ticket, size/M

#123 Add variable for position/coords when creating Player entity template
  workers/unity/Assets/BlankProject/Scripts/Config/EntityTemplates.cs
Labels: jira/no-ticket, size/XS
