Repository spatialos/gdk-for-unity-blank-project, pull requests merged in 2020-07, with the labels that each got.

#110 UTY-2607: Update linux queue
  .buildkite/premerge.steps.yaml
Labels: jira/UTY, size/XS

#109 Update buildkite artifact path to only use forward slash
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/launch.sh
Labels: jira/no-ticket, size/XS

#111 Entity representation
  .gitignore
  CHANGELOG.md
  gdk.pinned
  workers/unity/.gitignore
  workers/unity/Assets/BlankProject/BlankProject.asmdef
  workers/unity/Assets/BlankProject/BlankProject.asmdef.meta
  workers/unity/Assets/BlankProject/Scripts/Workers/MobileClientWorkerConnector.cs
  workers/unity/Assets/BlankProject/Scripts/Workers/UnityClientConnector.cs
  workers/unity/Assets/BlankProject/Scripts/Workers/UnityGameLogicConnector.cs
  workers/unity/Assets/Config/ClientPrefabMapping.asset
  workers/unity/Assets/Config/ClientPrefabMapping.asset.meta
  workers/unity/Assets/Config/GamelogicPrefabMapping.asset
  workers/unity/Assets/Config/GamelogicPrefabMapping.asset.meta
  workers/unity/Assets/Prefabs.meta
  workers/unity/Assets/Prefabs/Worker.meta
  workers/unity/Assets/Prefabs/Worker/ClientWorker.prefab
  workers/unity/Assets/Prefabs/Worker/ClientWorker.prefab.meta
  workers/unity/Assets/Prefabs/Worker/GameLogicWorker.prefab
  workers/unity/Assets/Prefabs/Worker/GameLogicWorker.prefab.meta
  workers/unity/Assets/Prefabs/Worker/MobileClientWorker.prefab
  workers/unity/Assets/Prefabs/Worker/MobileClientWorker.prefab.meta
Labels: jira/no-ticket, size/M

#112 UTY-2626: change sdk to 14.6.1
  spatialos.json
Labels: jira/UTY, size/XS

#113 UTY-2657: set max instances to 12 for windwos, linux and mac
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
Labels: jira/UTY, size/XS

#115 Update Worker SDK Version to 14.7.0
  CHANGELOG.md
  gdk.pinned
  spatialos.json
Labels: jira/no-ticket, size/XS
