Repository spatialos/gdk-for-unity-blank-project, pull requests merged in 2020-03, with the labels that each got.

#89 Basic port to QBI
  CHANGELOG.md
  cloud_launch.json
  default_launch.json
  snapshots/default.snapshot
  spatialos.json
  workers/unity/Assets/BlankProject.asmdef
  workers/unity/Assets/BlankProject/Scripts/Config/EntityTemplates.cs
  workers/unity/Assets/Editor/BlankProject.Editor.asmdef
  workers/unity/Assets/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Packages/manifest.json
  workers/unity/spatialos.MobileClient.worker.json
  workers/unity/spatialos.UnityClient.worker.json
  workers/unity/spatialos.UnityGameLogic.worker.json
Labels: jira/no-ticket, size/M

#90 Pass EntityId into Player EntityTemplate method
  CHANGELOG.md
  gdk.pinned
  workers/unity/Assets/BlankProject/Scripts/Config/EntityTemplates.cs
Labels: jira/no-ticket, size/XS

#92 Update README.md
  LICENSE.md
  README.md
Labels: jira/no-ticket, size/XS

#94 Fix "unbound variable" error in ci/bootstrap.sh
  ci/bootstrap.sh
Labels: jira/no-ticket, size/XS

#95 Remove unused scripts
  scripts/powershell/setup.ps1
  scripts/shell/setup.sh
Labels: jira/no-ticket, size/L

#96 Upgrade to Unity 2019.3
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  CHANGELOG.md
  gdk.pinned
  workers/unity/Assets/BlankProject/Scripts/Config.meta
  workers/unity/Assets/BlankProject/Scripts/Config/EntityTemplates.cs.meta
  workers/unity/Assets/Scenes/ClientScene.unity
  workers/unity/Assets/Scenes/DevelopmentScene.unity
  workers/unity/Assets/Scenes/GameLogicScene.unity
  workers/unity/Assets/Scenes/MobileClientScene.unity
  workers/unity/Packages/manifest.json
  workers/unity/ProjectSettings/AudioManager.asset
  workers/unity/ProjectSettings/DynamicsManager.asset
  workers/unity/ProjectSettings/EditorSettings.asset
  workers/unity/ProjectSettings/GraphicsSettings.asset
  workers/unity/ProjectSettings/Physics2DSettings.asset
  workers/unity/ProjectSettings/PresetManager.asset
  workers/unity/ProjectSettings/ProjectSettings.asset
  workers/unity/ProjectSettings/ProjectVersion.txt
  workers/unity/ProjectSettings/QualitySettings.asset
  workers/unity/ProjectSettings/VFXManager.asset
Labels: jira/no-ticket, size/L
